<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
<meta name="generator" content="pdoc 0.9.2" />
<title>raffiot.resource API documentation</title>
<meta name="description" content="Resource management module.
Ensure that create resources are always nicely released after use." />
<link rel="preload stylesheet" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/11.0.1/sanitize.min.css" integrity="sha256-PK9q560IAAa6WVRRh76LtCaI8pjTJ2z11v0miyNNjrs=" crossorigin>
<link rel="preload stylesheet" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/11.0.1/typography.min.css" integrity="sha256-7l/o7C8jubJiy74VsKTidCy1yBkRtiUGbVkYBylBqUg=" crossorigin>
<link rel="stylesheet preload" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/github.min.css" crossorigin>
<style>:root{--highlight-color:#fe9}.flex{display:flex !important}body{line-height:1.5em}#content{padding:20px}#sidebar{padding:30px;overflow:hidden}#sidebar > *:last-child{margin-bottom:2cm}.http-server-breadcrumbs{font-size:130%;margin:0 0 15px 0}#footer{font-size:.75em;padding:5px 30px;border-top:1px solid #ddd;text-align:right}#footer p{margin:0 0 0 1em;display:inline-block}#footer p:last-child{margin-right:30px}h1,h2,h3,h4,h5{font-weight:300}h1{font-size:2.5em;line-height:1.1em}h2{font-size:1.75em;margin:1em 0 .50em 0}h3{font-size:1.4em;margin:25px 0 10px 0}h4{margin:0;font-size:105%}h1:target,h2:target,h3:target,h4:target,h5:target,h6:target{background:var(--highlight-color);padding:.2em 0}a{color:#058;text-decoration:none;transition:color .3s ease-in-out}a:hover{color:#e82}.title code{font-weight:bold}h2[id^="header-"]{margin-top:2em}.ident{color:#900}pre code{background:#f8f8f8;font-size:.8em;line-height:1.4em}code{background:#f2f2f1;padding:1px 4px;overflow-wrap:break-word}h1 code{background:transparent}pre{background:#f8f8f8;border:0;border-top:1px solid #ccc;border-bottom:1px solid #ccc;margin:1em 0;padding:1ex}#http-server-module-list{display:flex;flex-flow:column}#http-server-module-list div{display:flex}#http-server-module-list dt{min-width:10%}#http-server-module-list p{margin-top:0}.toc ul,#index{list-style-type:none;margin:0;padding:0}#index code{background:transparent}#index h3{border-bottom:1px solid #ddd}#index ul{padding:0}#index h4{margin-top:.6em;font-weight:bold}@media (min-width:200ex){#index .two-column{column-count:2}}@media (min-width:300ex){#index .two-column{column-count:3}}dl{margin-bottom:2em}dl dl:last-child{margin-bottom:4em}dd{margin:0 0 1em 3em}#header-classes + dl > dd{margin-bottom:3em}dd dd{margin-left:2em}dd p{margin:10px 0}.name{background:#eee;font-weight:bold;font-size:.85em;padding:5px 10px;display:inline-block;min-width:40%}.name:hover{background:#e0e0e0}dt:target .name{background:var(--highlight-color)}.name > span:first-child{white-space:nowrap}.name.class > span:nth-child(2){margin-left:.4em}.inherited{color:#999;border-left:5px solid #eee;padding-left:1em}.inheritance em{font-style:normal;font-weight:bold}.desc h2{font-weight:400;font-size:1.25em}.desc h3{font-size:1em}.desc dt code{background:inherit}.source summary,.git-link-div{color:#666;text-align:right;font-weight:400;font-size:.8em;text-transform:uppercase}.source summary > *{white-space:nowrap;cursor:pointer}.git-link{color:inherit;margin-left:1em}.source pre{max-height:500px;overflow:auto;margin:0}.source pre code{font-size:12px;overflow:visible}.hlist{list-style:none}.hlist li{display:inline}.hlist li:after{content:',\2002'}.hlist li:last-child:after{content:none}.hlist .hlist{display:inline;padding-left:1em}img{max-width:100%}td{padding:0 .5em}.admonition{padding:.1em .5em;margin-bottom:1em}.admonition-title{font-weight:bold}.admonition.note,.admonition.info,.admonition.important{background:#aef}.admonition.todo,.admonition.versionadded,.admonition.tip,.admonition.hint{background:#dfd}.admonition.warning,.admonition.versionchanged,.admonition.deprecated{background:#fd4}.admonition.error,.admonition.danger,.admonition.caution{background:lightpink}</style>
<style media="screen and (min-width: 700px)">@media screen and (min-width:700px){#sidebar{width:30%;height:100vh;overflow:auto;position:sticky;top:0}#content{width:70%;max-width:100ch;padding:3em 4em;border-left:1px solid #ddd}pre code{font-size:1em}.item .name{font-size:1em}main{display:flex;flex-direction:row-reverse;justify-content:flex-end}.toc ul ul,#index ul{padding-left:1.5em}.toc > ul > li{margin-top:.5em}}</style>
<style media="print">@media print{#sidebar h1{page-break-before:always}.source{display:none}}@media print{*{background:transparent !important;color:#000 !important;box-shadow:none !important;text-shadow:none !important}a[href]:after{content:" (" attr(href) ")";font-size:90%}a[href][title]:after{content:none}abbr[title]:after{content:" (" attr(title) ")"}.ir a:after,a[href^="javascript:"]:after,a[href^="#"]:after{content:""}pre,blockquote{border:1px solid #999;page-break-inside:avoid}thead{display:table-header-group}tr,img{page-break-inside:avoid}img{max-width:100% !important}@page{margin:0.5cm}p,h2,h3{orphans:3;widows:3}h1,h2,h3,h4,h5,h6{page-break-after:avoid}}</style>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js" integrity="sha256-Uv3H6lx7dJmRfRvH8TH6kJD1TSK1aFcwgx+mdg3epi8=" crossorigin></script>
<script>window.addEventListener('DOMContentLoaded', () => hljs.initHighlighting())</script>
</head>
<body>
<main>
<article id="content">
<header>
<h1 class="title">Module <code>raffiot.resource</code></h1>
</header>
<section id="section-intro">
<p>Resource management module.
Ensure that create resources are always nicely released after use.</p>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">&#34;&#34;&#34;
Resource management module.
Ensure that create resources are always nicely released after use.
&#34;&#34;&#34;

from __future__ import annotations
from typing import TypeVar, Generic, Callable, Any, Tuple
from typing_extensions import final
from dataclasses import dataclass
from raffiot import result, io
from raffiot.io import IO

R = TypeVar(&#34;R&#34;)
E = TypeVar(&#34;E&#34;)
A = TypeVar(&#34;A&#34;)
X = TypeVar(&#34;X&#34;)
R2 = TypeVar(&#34;R2&#34;)
E2 = TypeVar(&#34;E2&#34;)
A2 = TypeVar(&#34;A2&#34;)


@final
@dataclass
class Resource(Generic[R, E, A]):
    &#34;&#34;&#34;
    Essentially an IO-powered data structure that produces resources of type A,
    can fail with errors of type E and read a context of type R.
    &#34;&#34;&#34;

    create: IO[R, E, Tuple[A, IO[R, Any, Any]]]
    &#34;&#34;&#34;
    IO to create one resource along with the IO for releasing it.
    
    On success, this IO must produce a Tuple[A, IO[R,Any,Any]:
        - The first value of the tuple, of type A, is the created resource.
        - The second value of the tuple, of type IO[R,Any,Any], is the IO that
            release the first value.
    
    For example:
        &gt;&gt;&gt; Resource(io.defer(lambda: open(&#34;file&#34;)).map(lambda a: (a, io.defer(a.close))))
    &#34;&#34;&#34;

    @final
    def use(self, fun: Callable[[A], IO[R, E, X]]) -&gt; IO[R, E, X]:
        &#34;&#34;&#34;
        Create a resource a:A and use it in fun.

        Once created, the resource a:A is guaranteed to be released (by running
        its releasing IO). The return value if the result of fun(a).

        This is the only way to use a resource.
        &#34;&#34;&#34;

        def safe_use(x: Tuple[A, IO[R, E, None]]) -&gt; IO[R, E, X]:
            a, close = x
            try:
                return (
                    fun(a)
                    .attempt()
                    .flat_map(lambda r: close.attempt().then(io.from_result(r)))
                )
            except Exception as exception:
                return close.attempt().then(io.panic(exception))

        return self.create.flat_map(safe_use)

    @final
    def map(self, f: Callable[[A], A2]) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Transform the created resource with f if the creation is successful.
        Do nothing otherwise.
        &#34;&#34;&#34;

        def safe_map(
            x: Tuple[A, IO[R, E, None]]
        ) -&gt; IO[R, E, Tuple[A2, IO[R, E, None]]]:
            a, close = x
            try:
                return io.pure((f(a), close))
            except Exception as exception:
                return close.attempt().then(io.panic(exception))

        return Resource(self.create.flat_map(safe_map))

    @final
    def flat_map(self, f: Callable[[A], Resource[R, E, A2]]) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Chain two Resource.
        The resource created by the first one (self) can be used to create the second (f).
        &#34;&#34;&#34;

        def safe_flat_map_a(
            xa: Tuple[A, IO[R, E, None]]
        ) -&gt; IO[R, E, Tuple[A2, IO[R, E, None]]]:
            a, close_a = xa
            try:

                def safe_flat_map_a2(
                    xa2: Tuple[A2, IO[R, Any, None]]
                ) -&gt; IO[R, E, Tuple[A2, IO[R, Any, None]]]:
                    a2, close_a2 = xa2
                    return io.pure((a2, close_a.attempt().then(close_a2)))

                return (
                    f(a)
                    .create.attempt()
                    .flat_map(
                        lambda r: r.fold(
                            safe_flat_map_a2,
                            lambda e: close_a.attempt().then(io.error(e)),
                            lambda p: close_a.attempt().then(io.panic(p)),
                        )
                    )
                )
            except Exception as exception:
                return close_a.attempt().then(io.panic(exception))

        return Resource(self.create.flat_map(safe_flat_map_a))

    @final
    def then(self, rs: Resource[R, E, A2]) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Chain two Resource.
        The resource created by the first one (self) is dropped.
        &#34;&#34;&#34;
        return self.flat_map(lambda _: rs)

    @final
    def ap(
        self: Resource[R, E, Callable[[X], A2]], rs: Resource[R, E, X]
    ) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Noting functions from X to A: X -&gt; A

        If self computes a function f: X -&gt; A
        and arg computes a value x: X
        then self.ap(arg) computes f(x): A
        &#34;&#34;&#34;
        return self.flat_map(lambda f: rs.map(f))

    @final
    def flatten(self: Resource[R, E, Resource[R, E, A]]) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        Concatenation function on Resource
        &#34;&#34;&#34;
        return self.flat_map(lambda x: x)

    # Reader API

    @final
    def contra_map_read(self, f: Callable[[R2], R]) -&gt; Resource[R2, E, A]:
        &#34;&#34;&#34;
        Transform the context with f.
        Note that f is not from R to R2 but from R2 to R!
        &#34;&#34;&#34;
        return Resource(
            self.create.contra_map_read(f).map(
                lambda x: (x[0], x[1].contra_map_read(f))
            )
        )

    # Error API

    @final
    def catch(self, handler: Callable[[E], Resource[R, E, A]]) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        React to errors (the except part of a try-except).

        On error, call the handler with the error.
        &#34;&#34;&#34;
        return Resource(self.create.catch(lambda e: handler(e).create))

    @final
    def map_error(self, f: Callable[[E], E2]) -&gt; Resource[R, E2, A]:
        &#34;&#34;&#34;
        Transform the stored error if the resource creation fails on an error.
        Do nothing otherwise.
        &#34;&#34;&#34;
        return Resource(self.create.map_error(f))

    # Panic

    @final
    def recover(
        self, handler: Callable[[Exception], Resource[R, E, A]]
    ) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        React to panics (the except part of a try-except).

        On panic, call the handler with the exception.
        &#34;&#34;&#34;
        return Resource(self.create.recover(lambda p: handler(p).create))

    @final
    def map_panic(self, f: Callable[[E], E2]) -&gt; Resource[R, E2, A]:
        &#34;&#34;&#34;
        Transform the exception stored if the computation fails on a panic.
        Do nothing otherwise.
        &#34;&#34;&#34;
        return Resource(
            self.create.map_panic(f).map(lambda x: (x[0], x[1].map_panic(f)))
        )

    @final
    def attempt(self) -&gt; IO[R, Any, result.Result[E, A]]:
        &#34;&#34;&#34;
        Transform this Resource that may fail into a Resource
        that never fails but creates a Result[E,A].

        - If self successfully computes a, then self.attempt() successfully computes Ok(a).
        - If self fails on error e, then self.attempt() successfully computes Error(e).
        - If self fails on panic p, then self.attempt() successfully computes Panic(p).

        Note that errors and panics stop the resource creation, unless a catch or
        recover reacts to such failures. But using map, flat_map, flatten and
        ap is sometimes easier than using catch and recover. attempt transforms
        a failed resource creation into a successful resource creation returning a failure,
        thus enabling you to use map, flat_map, ... to deal with errors.
        &#34;&#34;&#34;
        return Resource(
            self.create.attempt().map(
                lambda x: x.fold(
                    lambda v: (result.Ok(v[0]), v[1]),
                    lambda e: (result.Error(e), io.pure(None)),
                    lambda p: (result.Panic(p), io.pure(None)),
                )
            )
        )

    @final
    def finally_(self, rs: Resource[R, Any, Any]) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        After having computed self, but before returning its result,
        execute the rs Resource creation.

        This is extremely useful when you need to perform an action,
        unconditionally, at the end of a resource creation, without changing
        its result, like executing a lifted IO.
        &#34;&#34;&#34;
        return self.attempt().flat_map(lambda r: rs.attempt().then(from_result(r)))

    @final
    def on_failure(
        self, handler: Callable[[Result[E, Any]], IO[R, E, A]]
    ) -&gt; IO[R, E, A]:
        &#34;&#34;&#34;
        Combined form of catch and recover.
        React to any failure of the resource creation.
        Do nothing if the resource creation is successful.

        - The handler will be called on Error(e) if the resource creation fails with error e.
        - The handler will be called on Panic(p) if the resource creation fails with panic p.
        - The handler will never be called on Ok(a).
        &#34;&#34;&#34;
        return self.attempt().flat_map(
            lambda r: r.fold(
                pure,
                lambda e: handler(result.error(e)),
                lambda p: handler(result.panic(p)),
            )
        )


def liftIO(mio: IO[R, E, A]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Transform an IO into a Resource whose created resource if the result of the IO.
    The releasing IO does nothing.
    &#34;&#34;&#34;
    return Resource(mio.map(lambda a: (a, io.pure(None))))


def pure(a: A) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    A Resource that always returns the same constant.
    &#34;&#34;&#34;
    return Resource(io.pure((a, io.pure(None))))


def defer(deferred: Callable[[], A]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Defer a computation.

    The result of the Resource is the result of deferred().

    For more details, see io.defer
    &#34;&#34;&#34;
    return liftIO(io.defer(deferred))


def defer_resource(deferred: Callable[[], Resource[R, E, A]]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Make a function that returns an Resource, a Resource itself.

    This is extremely useful with recursive function that would normally blow
    the stack (raise a stack overflow exception). Deferring recursive calls
    eliminates stack overflow.

    For more information see io.defer_io
    &#34;&#34;&#34;
    return Resource(io.defer(deferred).flat_map(lambda rs: rs.create))


def read() -&gt; Resource[R, E, R]:
    &#34;&#34;&#34;
    Read the context.

    To execute a computation IO[R,E,A], you need to call the run method with
    some value r of type R: io.run(r). the read() action returns the value r
    given to run.

    Please note that the contra_map_read method can transform this value r.
    &#34;&#34;&#34;
    return liftIO(io.read())


def error(err: E) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Resource creation that always fails on the error err.
    &#34;&#34;&#34;
    return Resource(io.error(err))


def panic(exception: Exception) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Resource creation that always fails with the panic exception.
    &#34;&#34;&#34;
    return Resource(io.panic(exception))


def from_result(r: result.Result[E, A]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Resource creation that:
    - success if r is an Ok
    - fails with error e if r is Error(e)
    - fails with panic p if r is Panic(p)
    &#34;&#34;&#34;
    return r.fold(pure, error, panic)


def from_io_resource(mio: IO[R, E, Resource[R, E, A]]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Construct a Resource from an IO[R,E,Resource[R,E,A]]
    &#34;&#34;&#34;
    return Resource(mio.flat_map(lambda rs: rs.create))


def from_open_close_io(
    open: IO[R, E, A], close: Callable[[A], IO[R, Any, Any]]
) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Construct a Resource from an IO to open a resource and one to close it.
    &#34;&#34;&#34;
    return Resource(open.map(lambda a: (a, close(a))))


def from_open_close(
    open: Callable[[], A], close: Callable[[A], None]
) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Construct a Resource from a function to open a resource and one to close it.
    &#34;&#34;&#34;
    return Resource(io.defer(open).map(lambda a: (a, io.pure(a).map(close))))


def from_with(expr: Callable[[], Any]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Create a Resource from &#34;with&#34; python expression:

    &gt;&gt; with expr as x:
    &gt;&gt;     body

    is equivalent to

    &gt;&gt; from_with(lambda: expr)
    &#34;&#34;&#34;

    def manager_handler():
        manager = expr()
        enter = type(manager).__enter__
        exit = type(manager).__exit__
        (enter(manager), io.defer(lambda: exit(manager, None, None, None)))

    return Resource(io.defer(manager_handler))</code></pre>
</details>
</section>
<section>
</section>
<section>
</section>
<section>
<h2 class="section-title" id="header-functions">Functions</h2>
<dl>
<dt id="raffiot.resource.defer"><code class="name flex">
<span>def <span class="ident">defer</span></span>(<span>deferred: Callable[[], A]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Defer a computation.</p>
<p>The result of the Resource is the result of deferred().</p>
<p>For more details, see io.defer</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def defer(deferred: Callable[[], A]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Defer a computation.

    The result of the Resource is the result of deferred().

    For more details, see io.defer
    &#34;&#34;&#34;
    return liftIO(io.defer(deferred))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.defer_resource"><code class="name flex">
<span>def <span class="ident">defer_resource</span></span>(<span>deferred: Callable[[], <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, A]]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Make a function that returns an Resource, a Resource itself.</p>
<p>This is extremely useful with recursive function that would normally blow
the stack (raise a stack overflow exception). Deferring recursive calls
eliminates stack overflow.</p>
<p>For more information see io.defer_io</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def defer_resource(deferred: Callable[[], Resource[R, E, A]]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Make a function that returns an Resource, a Resource itself.

    This is extremely useful with recursive function that would normally blow
    the stack (raise a stack overflow exception). Deferring recursive calls
    eliminates stack overflow.

    For more information see io.defer_io
    &#34;&#34;&#34;
    return Resource(io.defer(deferred).flat_map(lambda rs: rs.create))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.error"><code class="name flex">
<span>def <span class="ident">error</span></span>(<span>err: E) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Resource creation that always fails on the error err.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def error(err: E) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Resource creation that always fails on the error err.
    &#34;&#34;&#34;
    return Resource(io.error(err))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.from_io_resource"><code class="name flex">
<span>def <span class="ident">from_io_resource</span></span>(<span>mio: IO[R, E, <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, A]]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Construct a Resource from an IO[R,E,Resource[R,E,A]]</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def from_io_resource(mio: IO[R, E, Resource[R, E, A]]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Construct a Resource from an IO[R,E,Resource[R,E,A]]
    &#34;&#34;&#34;
    return Resource(mio.flat_map(lambda rs: rs.create))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.from_open_close"><code class="name flex">
<span>def <span class="ident">from_open_close</span></span>(<span>open: Callable[[], A], close: Callable[[A], None]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Construct a Resource from a function to open a resource and one to close it.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def from_open_close(
    open: Callable[[], A], close: Callable[[A], None]
) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Construct a Resource from a function to open a resource and one to close it.
    &#34;&#34;&#34;
    return Resource(io.defer(open).map(lambda a: (a, io.pure(a).map(close))))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.from_open_close_io"><code class="name flex">
<span>def <span class="ident">from_open_close_io</span></span>(<span>open: IO[R, E, A], close: Callable[[A], IO[R, Any, Any]]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Construct a Resource from an IO to open a resource and one to close it.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def from_open_close_io(
    open: IO[R, E, A], close: Callable[[A], IO[R, Any, Any]]
) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Construct a Resource from an IO to open a resource and one to close it.
    &#34;&#34;&#34;
    return Resource(open.map(lambda a: (a, close(a))))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.from_result"><code class="name flex">
<span>def <span class="ident">from_result</span></span>(<span>r: result.Result[E, A]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Resource creation that:
- success if r is an Ok
- fails with error e if r is Error(e)
- fails with panic p if r is Panic(p)</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def from_result(r: result.Result[E, A]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Resource creation that:
    - success if r is an Ok
    - fails with error e if r is Error(e)
    - fails with panic p if r is Panic(p)
    &#34;&#34;&#34;
    return r.fold(pure, error, panic)</code></pre>
</details>
</dd>
<dt id="raffiot.resource.from_with"><code class="name flex">
<span>def <span class="ident">from_with</span></span>(<span>expr: Callable[[], Any]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Create a Resource from "with" python expression:</p>
<blockquote>
<blockquote>
<p>with expr as x:
body</p>
</blockquote>
</blockquote>
<p>is equivalent to</p>
<blockquote>
<blockquote>
<p>from_with(lambda: expr)</p>
</blockquote>
</blockquote></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def from_with(expr: Callable[[], Any]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Create a Resource from &#34;with&#34; python expression:

    &gt;&gt; with expr as x:
    &gt;&gt;     body

    is equivalent to

    &gt;&gt; from_with(lambda: expr)
    &#34;&#34;&#34;

    def manager_handler():
        manager = expr()
        enter = type(manager).__enter__
        exit = type(manager).__exit__
        (enter(manager), io.defer(lambda: exit(manager, None, None, None)))

    return Resource(io.defer(manager_handler))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.liftIO"><code class="name flex">
<span>def <span class="ident">liftIO</span></span>(<span>mio: IO[R, E, A]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform an IO into a Resource whose created resource if the result of the IO.
The releasing IO does nothing.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def liftIO(mio: IO[R, E, A]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Transform an IO into a Resource whose created resource if the result of the IO.
    The releasing IO does nothing.
    &#34;&#34;&#34;
    return Resource(mio.map(lambda a: (a, io.pure(None))))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.panic"><code class="name flex">
<span>def <span class="ident">panic</span></span>(<span>exception: Exception) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Resource creation that always fails with the panic exception.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def panic(exception: Exception) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Resource creation that always fails with the panic exception.
    &#34;&#34;&#34;
    return Resource(io.panic(exception))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.pure"><code class="name flex">
<span>def <span class="ident">pure</span></span>(<span>a: A) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>A Resource that always returns the same constant.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def pure(a: A) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    A Resource that always returns the same constant.
    &#34;&#34;&#34;
    return Resource(io.pure((a, io.pure(None))))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.read"><code class="name flex">
<span>def <span class="ident">read</span></span>(<span>) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~R]</span>
</code></dt>
<dd>
<div class="desc"><p>Read the context.</p>
<p>To execute a computation IO[R,E,A], you need to call the run method with
some value r of type R: io.run(r). the read() action returns the value r
given to run.</p>
<p>Please note that the contra_map_read method can transform this value r.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def read() -&gt; Resource[R, E, R]:
    &#34;&#34;&#34;
    Read the context.

    To execute a computation IO[R,E,A], you need to call the run method with
    some value r of type R: io.run(r). the read() action returns the value r
    given to run.

    Please note that the contra_map_read method can transform this value r.
    &#34;&#34;&#34;
    return liftIO(io.read())</code></pre>
</details>
</dd>
</dl>
</section>
<section>
<h2 class="section-title" id="header-classes">Classes</h2>
<dl>
<dt id="raffiot.resource.Resource"><code class="flex name class">
<span>class <span class="ident">Resource</span></span>
<span>(</span><span>create: IO[R, E, Tuple[A, IO[R, Any, Any]]])</span>
</code></dt>
<dd>
<div class="desc"><p>Essentially an IO-powered data structure that produces resources of type A,
can fail with errors of type E and read a context of type R.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
@dataclass
class Resource(Generic[R, E, A]):
    &#34;&#34;&#34;
    Essentially an IO-powered data structure that produces resources of type A,
    can fail with errors of type E and read a context of type R.
    &#34;&#34;&#34;

    create: IO[R, E, Tuple[A, IO[R, Any, Any]]]
    &#34;&#34;&#34;
    IO to create one resource along with the IO for releasing it.
    
    On success, this IO must produce a Tuple[A, IO[R,Any,Any]:
        - The first value of the tuple, of type A, is the created resource.
        - The second value of the tuple, of type IO[R,Any,Any], is the IO that
            release the first value.
    
    For example:
        &gt;&gt;&gt; Resource(io.defer(lambda: open(&#34;file&#34;)).map(lambda a: (a, io.defer(a.close))))
    &#34;&#34;&#34;

    @final
    def use(self, fun: Callable[[A], IO[R, E, X]]) -&gt; IO[R, E, X]:
        &#34;&#34;&#34;
        Create a resource a:A and use it in fun.

        Once created, the resource a:A is guaranteed to be released (by running
        its releasing IO). The return value if the result of fun(a).

        This is the only way to use a resource.
        &#34;&#34;&#34;

        def safe_use(x: Tuple[A, IO[R, E, None]]) -&gt; IO[R, E, X]:
            a, close = x
            try:
                return (
                    fun(a)
                    .attempt()
                    .flat_map(lambda r: close.attempt().then(io.from_result(r)))
                )
            except Exception as exception:
                return close.attempt().then(io.panic(exception))

        return self.create.flat_map(safe_use)

    @final
    def map(self, f: Callable[[A], A2]) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Transform the created resource with f if the creation is successful.
        Do nothing otherwise.
        &#34;&#34;&#34;

        def safe_map(
            x: Tuple[A, IO[R, E, None]]
        ) -&gt; IO[R, E, Tuple[A2, IO[R, E, None]]]:
            a, close = x
            try:
                return io.pure((f(a), close))
            except Exception as exception:
                return close.attempt().then(io.panic(exception))

        return Resource(self.create.flat_map(safe_map))

    @final
    def flat_map(self, f: Callable[[A], Resource[R, E, A2]]) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Chain two Resource.
        The resource created by the first one (self) can be used to create the second (f).
        &#34;&#34;&#34;

        def safe_flat_map_a(
            xa: Tuple[A, IO[R, E, None]]
        ) -&gt; IO[R, E, Tuple[A2, IO[R, E, None]]]:
            a, close_a = xa
            try:

                def safe_flat_map_a2(
                    xa2: Tuple[A2, IO[R, Any, None]]
                ) -&gt; IO[R, E, Tuple[A2, IO[R, Any, None]]]:
                    a2, close_a2 = xa2
                    return io.pure((a2, close_a.attempt().then(close_a2)))

                return (
                    f(a)
                    .create.attempt()
                    .flat_map(
                        lambda r: r.fold(
                            safe_flat_map_a2,
                            lambda e: close_a.attempt().then(io.error(e)),
                            lambda p: close_a.attempt().then(io.panic(p)),
                        )
                    )
                )
            except Exception as exception:
                return close_a.attempt().then(io.panic(exception))

        return Resource(self.create.flat_map(safe_flat_map_a))

    @final
    def then(self, rs: Resource[R, E, A2]) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Chain two Resource.
        The resource created by the first one (self) is dropped.
        &#34;&#34;&#34;
        return self.flat_map(lambda _: rs)

    @final
    def ap(
        self: Resource[R, E, Callable[[X], A2]], rs: Resource[R, E, X]
    ) -&gt; Resource[R, E, A2]:
        &#34;&#34;&#34;
        Noting functions from X to A: X -&gt; A

        If self computes a function f: X -&gt; A
        and arg computes a value x: X
        then self.ap(arg) computes f(x): A
        &#34;&#34;&#34;
        return self.flat_map(lambda f: rs.map(f))

    @final
    def flatten(self: Resource[R, E, Resource[R, E, A]]) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        Concatenation function on Resource
        &#34;&#34;&#34;
        return self.flat_map(lambda x: x)

    # Reader API

    @final
    def contra_map_read(self, f: Callable[[R2], R]) -&gt; Resource[R2, E, A]:
        &#34;&#34;&#34;
        Transform the context with f.
        Note that f is not from R to R2 but from R2 to R!
        &#34;&#34;&#34;
        return Resource(
            self.create.contra_map_read(f).map(
                lambda x: (x[0], x[1].contra_map_read(f))
            )
        )

    # Error API

    @final
    def catch(self, handler: Callable[[E], Resource[R, E, A]]) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        React to errors (the except part of a try-except).

        On error, call the handler with the error.
        &#34;&#34;&#34;
        return Resource(self.create.catch(lambda e: handler(e).create))

    @final
    def map_error(self, f: Callable[[E], E2]) -&gt; Resource[R, E2, A]:
        &#34;&#34;&#34;
        Transform the stored error if the resource creation fails on an error.
        Do nothing otherwise.
        &#34;&#34;&#34;
        return Resource(self.create.map_error(f))

    # Panic

    @final
    def recover(
        self, handler: Callable[[Exception], Resource[R, E, A]]
    ) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        React to panics (the except part of a try-except).

        On panic, call the handler with the exception.
        &#34;&#34;&#34;
        return Resource(self.create.recover(lambda p: handler(p).create))

    @final
    def map_panic(self, f: Callable[[E], E2]) -&gt; Resource[R, E2, A]:
        &#34;&#34;&#34;
        Transform the exception stored if the computation fails on a panic.
        Do nothing otherwise.
        &#34;&#34;&#34;
        return Resource(
            self.create.map_panic(f).map(lambda x: (x[0], x[1].map_panic(f)))
        )

    @final
    def attempt(self) -&gt; IO[R, Any, result.Result[E, A]]:
        &#34;&#34;&#34;
        Transform this Resource that may fail into a Resource
        that never fails but creates a Result[E,A].

        - If self successfully computes a, then self.attempt() successfully computes Ok(a).
        - If self fails on error e, then self.attempt() successfully computes Error(e).
        - If self fails on panic p, then self.attempt() successfully computes Panic(p).

        Note that errors and panics stop the resource creation, unless a catch or
        recover reacts to such failures. But using map, flat_map, flatten and
        ap is sometimes easier than using catch and recover. attempt transforms
        a failed resource creation into a successful resource creation returning a failure,
        thus enabling you to use map, flat_map, ... to deal with errors.
        &#34;&#34;&#34;
        return Resource(
            self.create.attempt().map(
                lambda x: x.fold(
                    lambda v: (result.Ok(v[0]), v[1]),
                    lambda e: (result.Error(e), io.pure(None)),
                    lambda p: (result.Panic(p), io.pure(None)),
                )
            )
        )

    @final
    def finally_(self, rs: Resource[R, Any, Any]) -&gt; Resource[R, E, A]:
        &#34;&#34;&#34;
        After having computed self, but before returning its result,
        execute the rs Resource creation.

        This is extremely useful when you need to perform an action,
        unconditionally, at the end of a resource creation, without changing
        its result, like executing a lifted IO.
        &#34;&#34;&#34;
        return self.attempt().flat_map(lambda r: rs.attempt().then(from_result(r)))

    @final
    def on_failure(
        self, handler: Callable[[Result[E, Any]], IO[R, E, A]]
    ) -&gt; IO[R, E, A]:
        &#34;&#34;&#34;
        Combined form of catch and recover.
        React to any failure of the resource creation.
        Do nothing if the resource creation is successful.

        - The handler will be called on Error(e) if the resource creation fails with error e.
        - The handler will be called on Panic(p) if the resource creation fails with panic p.
        - The handler will never be called on Ok(a).
        &#34;&#34;&#34;
        return self.attempt().flat_map(
            lambda r: r.fold(
                pure,
                lambda e: handler(result.error(e)),
                lambda p: handler(result.panic(p)),
            )
        )</code></pre>
</details>
<h3>Ancestors</h3>
<ul class="hlist">
<li>typing.Generic</li>
</ul>
<h3>Class variables</h3>
<dl>
<dt id="raffiot.resource.Resource.create"><code class="name">var <span class="ident">create</span> : <a title="raffiot.io.IO" href="io.html#raffiot.io.IO">IO</a>[~R, ~E, typing.Tuple[~A, <a title="raffiot.io.IO" href="io.html#raffiot.io.IO">IO</a>[~R, typing.Any, typing.Any]]]</code></dt>
<dd>
<div class="desc"><p>IO to create one resource along with the IO for releasing it.</p>
<p>On success, this IO must produce a Tuple[A, IO[R,Any,Any]:
- The first value of the tuple, of type A, is the created resource.
- The second value of the tuple, of type IO[R,Any,Any], is the IO that
release the first value.</p>
<p>For example:
&gt;&gt;&gt; Resource(io.defer(lambda: open("file")).map(lambda a: (a, io.defer(a.close))))</p></div>
</dd>
</dl>
<h3>Methods</h3>
<dl>
<dt id="raffiot.resource.Resource.ap"><code class="name flex">
<span>def <span class="ident">ap</span></span>(<span>self: <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, Callable[[X], A2]], rs: <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, X]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A2]</span>
</code></dt>
<dd>
<div class="desc"><p>Noting functions from X to A: X -&gt; A</p>
<p>If self computes a function f: X -&gt; A
and arg computes a value x: X
then self.ap(arg) computes f(x): A</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def ap(
    self: Resource[R, E, Callable[[X], A2]], rs: Resource[R, E, X]
) -&gt; Resource[R, E, A2]:
    &#34;&#34;&#34;
    Noting functions from X to A: X -&gt; A

    If self computes a function f: X -&gt; A
    and arg computes a value x: X
    then self.ap(arg) computes f(x): A
    &#34;&#34;&#34;
    return self.flat_map(lambda f: rs.map(f))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.attempt"><code class="name flex">
<span>def <span class="ident">attempt</span></span>(<span>self) ‑> <a title="raffiot.io.IO" href="io.html#raffiot.io.IO">IO</a>[~R, typing.Any, <a title="raffiot.result.Result" href="result.html#raffiot.result.Result">Result</a>[~E, ~A]]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform this Resource that may fail into a Resource
that never fails but creates a Result[E,A].</p>
<ul>
<li>If self successfully computes a, then self.attempt() successfully computes Ok(a).</li>
<li>If self fails on error e, then self.attempt() successfully computes Error(e).</li>
<li>If self fails on panic p, then self.attempt() successfully computes Panic(p).</li>
</ul>
<p>Note that errors and panics stop the resource creation, unless a catch or
recover reacts to such failures. But using map, flat_map, flatten and
ap is sometimes easier than using catch and recover. attempt transforms
a failed resource creation into a successful resource creation returning a failure,
thus enabling you to use map, flat_map, &hellip; to deal with errors.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def attempt(self) -&gt; IO[R, Any, result.Result[E, A]]:
    &#34;&#34;&#34;
    Transform this Resource that may fail into a Resource
    that never fails but creates a Result[E,A].

    - If self successfully computes a, then self.attempt() successfully computes Ok(a).
    - If self fails on error e, then self.attempt() successfully computes Error(e).
    - If self fails on panic p, then self.attempt() successfully computes Panic(p).

    Note that errors and panics stop the resource creation, unless a catch or
    recover reacts to such failures. But using map, flat_map, flatten and
    ap is sometimes easier than using catch and recover. attempt transforms
    a failed resource creation into a successful resource creation returning a failure,
    thus enabling you to use map, flat_map, ... to deal with errors.
    &#34;&#34;&#34;
    return Resource(
        self.create.attempt().map(
            lambda x: x.fold(
                lambda v: (result.Ok(v[0]), v[1]),
                lambda e: (result.Error(e), io.pure(None)),
                lambda p: (result.Panic(p), io.pure(None)),
            )
        )
    )</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.catch"><code class="name flex">
<span>def <span class="ident">catch</span></span>(<span>self, handler: Callable[[E], <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, A]]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>React to errors (the except part of a try-except).</p>
<p>On error, call the handler with the error.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def catch(self, handler: Callable[[E], Resource[R, E, A]]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    React to errors (the except part of a try-except).

    On error, call the handler with the error.
    &#34;&#34;&#34;
    return Resource(self.create.catch(lambda e: handler(e).create))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.contra_map_read"><code class="name flex">
<span>def <span class="ident">contra_map_read</span></span>(<span>self, f: Callable[[R2], R]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R2, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform the context with f.
Note that f is not from R to R2 but from R2 to R!</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def contra_map_read(self, f: Callable[[R2], R]) -&gt; Resource[R2, E, A]:
    &#34;&#34;&#34;
    Transform the context with f.
    Note that f is not from R to R2 but from R2 to R!
    &#34;&#34;&#34;
    return Resource(
        self.create.contra_map_read(f).map(
            lambda x: (x[0], x[1].contra_map_read(f))
        )
    )</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.finally_"><code class="name flex">
<span>def <span class="ident">finally_</span></span>(<span>self, rs: <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, Any, Any]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>After having computed self, but before returning its result,
execute the rs Resource creation.</p>
<p>This is extremely useful when you need to perform an action,
unconditionally, at the end of a resource creation, without changing
its result, like executing a lifted IO.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def finally_(self, rs: Resource[R, Any, Any]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    After having computed self, but before returning its result,
    execute the rs Resource creation.

    This is extremely useful when you need to perform an action,
    unconditionally, at the end of a resource creation, without changing
    its result, like executing a lifted IO.
    &#34;&#34;&#34;
    return self.attempt().flat_map(lambda r: rs.attempt().then(from_result(r)))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.flat_map"><code class="name flex">
<span>def <span class="ident">flat_map</span></span>(<span>self, f: Callable[[A], <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, A2]]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A2]</span>
</code></dt>
<dd>
<div class="desc"><p>Chain two Resource.
The resource created by the first one (self) can be used to create the second (f).</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def flat_map(self, f: Callable[[A], Resource[R, E, A2]]) -&gt; Resource[R, E, A2]:
    &#34;&#34;&#34;
    Chain two Resource.
    The resource created by the first one (self) can be used to create the second (f).
    &#34;&#34;&#34;

    def safe_flat_map_a(
        xa: Tuple[A, IO[R, E, None]]
    ) -&gt; IO[R, E, Tuple[A2, IO[R, E, None]]]:
        a, close_a = xa
        try:

            def safe_flat_map_a2(
                xa2: Tuple[A2, IO[R, Any, None]]
            ) -&gt; IO[R, E, Tuple[A2, IO[R, Any, None]]]:
                a2, close_a2 = xa2
                return io.pure((a2, close_a.attempt().then(close_a2)))

            return (
                f(a)
                .create.attempt()
                .flat_map(
                    lambda r: r.fold(
                        safe_flat_map_a2,
                        lambda e: close_a.attempt().then(io.error(e)),
                        lambda p: close_a.attempt().then(io.panic(p)),
                    )
                )
            )
        except Exception as exception:
            return close_a.attempt().then(io.panic(exception))

    return Resource(self.create.flat_map(safe_flat_map_a))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.flatten"><code class="name flex">
<span>def <span class="ident">flatten</span></span>(<span>self: <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, A]]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Concatenation function on Resource</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def flatten(self: Resource[R, E, Resource[R, E, A]]) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    Concatenation function on Resource
    &#34;&#34;&#34;
    return self.flat_map(lambda x: x)</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.map"><code class="name flex">
<span>def <span class="ident">map</span></span>(<span>self, f: Callable[[A], A2]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A2]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform the created resource with f if the creation is successful.
Do nothing otherwise.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def map(self, f: Callable[[A], A2]) -&gt; Resource[R, E, A2]:
    &#34;&#34;&#34;
    Transform the created resource with f if the creation is successful.
    Do nothing otherwise.
    &#34;&#34;&#34;

    def safe_map(
        x: Tuple[A, IO[R, E, None]]
    ) -&gt; IO[R, E, Tuple[A2, IO[R, E, None]]]:
        a, close = x
        try:
            return io.pure((f(a), close))
        except Exception as exception:
            return close.attempt().then(io.panic(exception))

    return Resource(self.create.flat_map(safe_map))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.map_error"><code class="name flex">
<span>def <span class="ident">map_error</span></span>(<span>self, f: Callable[[E], E2]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E2, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform the stored error if the resource creation fails on an error.
Do nothing otherwise.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def map_error(self, f: Callable[[E], E2]) -&gt; Resource[R, E2, A]:
    &#34;&#34;&#34;
    Transform the stored error if the resource creation fails on an error.
    Do nothing otherwise.
    &#34;&#34;&#34;
    return Resource(self.create.map_error(f))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.map_panic"><code class="name flex">
<span>def <span class="ident">map_panic</span></span>(<span>self, f: Callable[[E], E2]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E2, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform the exception stored if the computation fails on a panic.
Do nothing otherwise.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def map_panic(self, f: Callable[[E], E2]) -&gt; Resource[R, E2, A]:
    &#34;&#34;&#34;
    Transform the exception stored if the computation fails on a panic.
    Do nothing otherwise.
    &#34;&#34;&#34;
    return Resource(
        self.create.map_panic(f).map(lambda x: (x[0], x[1].map_panic(f)))
    )</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.on_failure"><code class="name flex">
<span>def <span class="ident">on_failure</span></span>(<span>self, handler: Callable[[Result[E, Any]], IO[R, E, A]]) ‑> IO[R, E, A]</span>
</code></dt>
<dd>
<div class="desc"><p>Combined form of catch and recover.
React to any failure of the resource creation.
Do nothing if the resource creation is successful.</p>
<ul>
<li>The handler will be called on Error(e) if the resource creation fails with error e.</li>
<li>The handler will be called on Panic(p) if the resource creation fails with panic p.</li>
<li>The handler will never be called on Ok(a).</li>
</ul></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def on_failure(
    self, handler: Callable[[Result[E, Any]], IO[R, E, A]]
) -&gt; IO[R, E, A]:
    &#34;&#34;&#34;
    Combined form of catch and recover.
    React to any failure of the resource creation.
    Do nothing if the resource creation is successful.

    - The handler will be called on Error(e) if the resource creation fails with error e.
    - The handler will be called on Panic(p) if the resource creation fails with panic p.
    - The handler will never be called on Ok(a).
    &#34;&#34;&#34;
    return self.attempt().flat_map(
        lambda r: r.fold(
            pure,
            lambda e: handler(result.error(e)),
            lambda p: handler(result.panic(p)),
        )
    )</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.recover"><code class="name flex">
<span>def <span class="ident">recover</span></span>(<span>self, handler: Callable[[Exception], <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, A]]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>React to panics (the except part of a try-except).</p>
<p>On panic, call the handler with the exception.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def recover(
    self, handler: Callable[[Exception], Resource[R, E, A]]
) -&gt; Resource[R, E, A]:
    &#34;&#34;&#34;
    React to panics (the except part of a try-except).

    On panic, call the handler with the exception.
    &#34;&#34;&#34;
    return Resource(self.create.recover(lambda p: handler(p).create))</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.then"><code class="name flex">
<span>def <span class="ident">then</span></span>(<span>self, rs: <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[R, E, A2]) ‑> <a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a>[~R, ~E, ~A2]</span>
</code></dt>
<dd>
<div class="desc"><p>Chain two Resource.
The resource created by the first one (self) is dropped.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def then(self, rs: Resource[R, E, A2]) -&gt; Resource[R, E, A2]:
    &#34;&#34;&#34;
    Chain two Resource.
    The resource created by the first one (self) is dropped.
    &#34;&#34;&#34;
    return self.flat_map(lambda _: rs)</code></pre>
</details>
</dd>
<dt id="raffiot.resource.Resource.use"><code class="name flex">
<span>def <span class="ident">use</span></span>(<span>self, fun: Callable[[A], IO[R, E, X]]) ‑> <a title="raffiot.io.IO" href="io.html#raffiot.io.IO">IO</a>[~R, ~E, ~X]</span>
</code></dt>
<dd>
<div class="desc"><p>Create a resource a:A and use it in fun.</p>
<p>Once created, the resource a:A is guaranteed to be released (by running
its releasing IO). The return value if the result of fun(a).</p>
<p>This is the only way to use a resource.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def use(self, fun: Callable[[A], IO[R, E, X]]) -&gt; IO[R, E, X]:
    &#34;&#34;&#34;
    Create a resource a:A and use it in fun.

    Once created, the resource a:A is guaranteed to be released (by running
    its releasing IO). The return value if the result of fun(a).

    This is the only way to use a resource.
    &#34;&#34;&#34;

    def safe_use(x: Tuple[A, IO[R, E, None]]) -&gt; IO[R, E, X]:
        a, close = x
        try:
            return (
                fun(a)
                .attempt()
                .flat_map(lambda r: close.attempt().then(io.from_result(r)))
            )
        except Exception as exception:
            return close.attempt().then(io.panic(exception))

    return self.create.flat_map(safe_use)</code></pre>
</details>
</dd>
</dl>
</dd>
</dl>
</section>
</article>
<nav id="sidebar">
<h1>Index</h1>
<div class="toc">
<ul></ul>
</div>
<ul id="index">
<li><h3>Super-module</h3>
<ul>
<li><code><a title="raffiot" href="index.html">raffiot</a></code></li>
</ul>
</li>
<li><h3><a href="#header-functions">Functions</a></h3>
<ul class="two-column">
<li><code><a title="raffiot.resource.defer" href="#raffiot.resource.defer">defer</a></code></li>
<li><code><a title="raffiot.resource.defer_resource" href="#raffiot.resource.defer_resource">defer_resource</a></code></li>
<li><code><a title="raffiot.resource.error" href="#raffiot.resource.error">error</a></code></li>
<li><code><a title="raffiot.resource.from_io_resource" href="#raffiot.resource.from_io_resource">from_io_resource</a></code></li>
<li><code><a title="raffiot.resource.from_open_close" href="#raffiot.resource.from_open_close">from_open_close</a></code></li>
<li><code><a title="raffiot.resource.from_open_close_io" href="#raffiot.resource.from_open_close_io">from_open_close_io</a></code></li>
<li><code><a title="raffiot.resource.from_result" href="#raffiot.resource.from_result">from_result</a></code></li>
<li><code><a title="raffiot.resource.from_with" href="#raffiot.resource.from_with">from_with</a></code></li>
<li><code><a title="raffiot.resource.liftIO" href="#raffiot.resource.liftIO">liftIO</a></code></li>
<li><code><a title="raffiot.resource.panic" href="#raffiot.resource.panic">panic</a></code></li>
<li><code><a title="raffiot.resource.pure" href="#raffiot.resource.pure">pure</a></code></li>
<li><code><a title="raffiot.resource.read" href="#raffiot.resource.read">read</a></code></li>
</ul>
</li>
<li><h3><a href="#header-classes">Classes</a></h3>
<ul>
<li>
<h4><code><a title="raffiot.resource.Resource" href="#raffiot.resource.Resource">Resource</a></code></h4>
<ul class="two-column">
<li><code><a title="raffiot.resource.Resource.ap" href="#raffiot.resource.Resource.ap">ap</a></code></li>
<li><code><a title="raffiot.resource.Resource.attempt" href="#raffiot.resource.Resource.attempt">attempt</a></code></li>
<li><code><a title="raffiot.resource.Resource.catch" href="#raffiot.resource.Resource.catch">catch</a></code></li>
<li><code><a title="raffiot.resource.Resource.contra_map_read" href="#raffiot.resource.Resource.contra_map_read">contra_map_read</a></code></li>
<li><code><a title="raffiot.resource.Resource.create" href="#raffiot.resource.Resource.create">create</a></code></li>
<li><code><a title="raffiot.resource.Resource.finally_" href="#raffiot.resource.Resource.finally_">finally_</a></code></li>
<li><code><a title="raffiot.resource.Resource.flat_map" href="#raffiot.resource.Resource.flat_map">flat_map</a></code></li>
<li><code><a title="raffiot.resource.Resource.flatten" href="#raffiot.resource.Resource.flatten">flatten</a></code></li>
<li><code><a title="raffiot.resource.Resource.map" href="#raffiot.resource.Resource.map">map</a></code></li>
<li><code><a title="raffiot.resource.Resource.map_error" href="#raffiot.resource.Resource.map_error">map_error</a></code></li>
<li><code><a title="raffiot.resource.Resource.map_panic" href="#raffiot.resource.Resource.map_panic">map_panic</a></code></li>
<li><code><a title="raffiot.resource.Resource.on_failure" href="#raffiot.resource.Resource.on_failure">on_failure</a></code></li>
<li><code><a title="raffiot.resource.Resource.recover" href="#raffiot.resource.Resource.recover">recover</a></code></li>
<li><code><a title="raffiot.resource.Resource.then" href="#raffiot.resource.Resource.then">then</a></code></li>
<li><code><a title="raffiot.resource.Resource.use" href="#raffiot.resource.Resource.use">use</a></code></li>
</ul>
</li>
</ul>
</li>
</ul>
</nav>
</main>
<footer id="footer">
<p>Generated by <a href="https://pdoc3.github.io/pdoc"><cite>pdoc</cite> 0.9.2</a>.</p>
</footer>
</body>
</html>